package com.elvin.course.view;

import com.elvin.course.DBUtil.Constants;
import com.elvin.course.dao.CourseDao;
import com.elvin.course.dao.CourseDaoImpl;
import com.elvin.course.dao.StudentDao;
import com.elvin.course.dao.StudentDaoImpl;
import com.elvin.course.dao.TeacherDao;
import com.elvin.course.dao.TeacherDaoImpl;
import com.elvin.course.model.Course;
import com.elvin.course.model.Student;
import com.elvin.course.model.Teacher;
import com.elvin.course.model.User;
import java.awt.Color;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Khal_vh04
 */
public class JFrameAdmin extends javax.swing.JFrame {

    private StudentDao studentDao = new StudentDaoImpl();
    private TeacherDao teacherDao = new TeacherDaoImpl();
    private CourseDao courseDao = new CourseDaoImpl();
    private Map<String, Integer> mapCourse = new HashMap<>();
    private  Integer idTeacher; 
    private Integer idCourse ;

    public JFrameAdmin() {
        initComponents();
        customInit();
        setStudentTable();
        setTeacherTable();
        setCourseTable();
    }
    public JFrameAdmin(User user){
       user=new User();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedAdmin = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelStudent = new javax.swing.JPanel();
        jPanelStudenttable = new javax.swing.JPanel();
        jScrollPanelStudent = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jButtonEditStudent = new javax.swing.JButton();
        jButtonDeleteStudent = new javax.swing.JButton();
        jTextFieldSearchStudent = new javax.swing.JTextField();
        jPanelTeacher = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTeacher = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButtonEditTeacher = new javax.swing.JButton();
        jButtonDeleteTeacher = new javax.swing.JButton();
        jTextFieldSearchTeacher = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTeacherFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTeacherLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCourse1 = new javax.swing.JComboBox<>();
        jButtonRegisterTeacher = new javax.swing.JButton();
        jButtonUpdateTeacher = new javax.swing.JButton();
        jButtonResetTeacher = new javax.swing.JButton();
        jPanelCourse = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCourse = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jButtonEditCourse = new javax.swing.JButton();
        jButtonDeleteCourse = new javax.swing.JButton();
        jTextFieldSearchCourse = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCourseName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDuration = new javax.swing.JTextField();
        jButtonRegisterCourse = new javax.swing.JButton();
        jButtonUpdateCourse = new javax.swing.JButton();
        jButtonResetCourse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jTabbedAdmin.addTab("Admin", jPanel1);

        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanelStudent.setViewportView(jTableStudent);

        javax.swing.GroupLayout jPanelStudenttableLayout = new javax.swing.GroupLayout(jPanelStudenttable);
        jPanelStudenttable.setLayout(jPanelStudenttableLayout);
        jPanelStudenttableLayout.setHorizontalGroup(
            jPanelStudenttableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudenttableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPanelStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelStudenttableLayout.setVerticalGroup(
            jPanelStudenttableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudenttableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPanelStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonEditStudent.setText("Edit");
        jButtonEditStudent.setEnabled(false);
        jButtonEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditStudentActionPerformed(evt);
            }
        });

        jButtonDeleteStudent.setText("Delete");
        jButtonDeleteStudent.setEnabled(false);
        jButtonDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteStudentActionPerformed(evt);
            }
        });

        jTextFieldSearchStudent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSearchStudentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSearchStudentFocusLost(evt);
            }
        });
        jTextFieldSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStudentLayout = new javax.swing.GroupLayout(jPanelStudent);
        jPanelStudent.setLayout(jPanelStudentLayout);
        jPanelStudentLayout.setHorizontalGroup(
            jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelStudenttable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelStudentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFieldSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelStudentLayout.setVerticalGroup(
            jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelStudenttable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedAdmin.addTab("Student", jPanelStudent);

        jTableTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableTeacher);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonEditTeacher.setText("Edit Teacher");
        jButtonEditTeacher.setEnabled(false);
        jButtonEditTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditTeacherActionPerformed(evt);
            }
        });

        jButtonDeleteTeacher.setText("Delete Teacher");
        jButtonDeleteTeacher.setEnabled(false);
        jButtonDeleteTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteTeacherActionPerformed(evt);
            }
        });

        jTextFieldSearchTeacher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSearchTeacherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSearchTeacherFocusLost(evt);
            }
        });
        jTextFieldSearchTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldSearchTeacherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldSearchTeacherMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldSearchTeacherMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldSearchTeacherMouseReleased(evt);
            }
        });
        jTextFieldSearchTeacher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchTeacherKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTextFieldSearchTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTextFieldSearchTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDeleteTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Teacher"));

        jLabel1.setText("Teacher First Name");

        jLabel2.setText("Teacher Last Name");

        jLabel3.setText("Course");

        jButtonRegisterTeacher.setText("Register ");
        jButtonRegisterTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterTeacherActionPerformed(evt);
            }
        });

        jButtonUpdateTeacher.setText("Update");
        jButtonUpdateTeacher.setEnabled(false);
        jButtonUpdateTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateTeacherActionPerformed(evt);
            }
        });

        jButtonResetTeacher.setText("Reset");
        jButtonResetTeacher.setEnabled(false);
        jButtonResetTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTeacherFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldTeacherLastName)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(jButtonRegisterTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jComboBoxCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonResetTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegisterTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTeacherFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTeacherLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdateTeacher)
                    .addComponent(jButtonResetTeacher))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelTeacherLayout = new javax.swing.GroupLayout(jPanelTeacher);
        jPanelTeacher.setLayout(jPanelTeacherLayout);
        jPanelTeacherLayout.setHorizontalGroup(
            jPanelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeacherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTeacherLayout.setVerticalGroup(
            jPanelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeacherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedAdmin.addTab("Teacher", jPanelTeacher);

        jTableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableCourse);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonEditCourse.setText("Edit Course");
        jButtonEditCourse.setEnabled(false);
        jButtonEditCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditCourseActionPerformed(evt);
            }
        });

        jButtonDeleteCourse.setText("Delete Course");
        jButtonDeleteCourse.setEnabled(false);
        jButtonDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCourseActionPerformed(evt);
            }
        });

        jTextFieldSearchCourse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSearchCourseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSearchCourseFocusLost(evt);
            }
        });
        jTextFieldSearchCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldSearchCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldSearchCourseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldSearchCourseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldSearchCourseMouseReleased(evt);
            }
        });
        jTextFieldSearchCourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchCourseKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTextFieldSearchCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jTextFieldSearchCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDeleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Teacher"));

        jLabel4.setText("Course Name");

        jLabel5.setText("Course Duration");

        jButtonRegisterCourse.setText("Register ");
        jButtonRegisterCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterCourseActionPerformed(evt);
            }
        });

        jButtonUpdateCourse.setText("Update");
        jButtonUpdateCourse.setEnabled(false);
        jButtonUpdateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateCourseActionPerformed(evt);
            }
        });

        jButtonResetCourse.setText("Reset");
        jButtonResetCourse.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldDuration)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jButtonRegisterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButtonResetCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegisterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdateCourse)
                    .addComponent(jButtonResetCourse))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCourseLayout = new javax.swing.GroupLayout(jPanelCourse);
        jPanelCourse.setLayout(jPanelCourseLayout);
        jPanelCourseLayout.setHorizontalGroup(
            jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCourseLayout.setVerticalGroup(
            jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedAdmin.addTab("Course", jPanelCourse);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedAdmin)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedAdmin)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditTeacherActionPerformed
        
        
        jButtonUpdateTeacher.setEnabled(true);
        jButtonRegisterTeacher.setEnabled(false);
        jButtonResetTeacher.setEnabled(true);
         idTeacher = (Integer) jTableTeacher.getValueAt(jTableTeacher.getSelectedRow(), 0);
        Teacher teacher = teacherDao.getTeacherById(idTeacher);
        jTextFieldTeacherFirstName.setText(teacher.getFirstName());
        jTextFieldTeacherLastName.setText(teacher.getLastName());
        jComboBoxCourse1.setSelectedItem(teacher.getCourse().getCourseName());
        
        
    }//GEN-LAST:event_jButtonEditTeacherActionPerformed

    private void jButtonDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteStudentActionPerformed
        Integer id = (Integer) jTableStudent.getValueAt(jTableStudent.getSelectedRow(), 0);
        if (id != null) {
            studentDao.deleteStudent(id);
            setStudentTable();
        }
    }//GEN-LAST:event_jButtonDeleteStudentActionPerformed

    private void jButtonEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditStudentActionPerformed
        Integer id = (Integer) jTableStudent.getValueAt(jTableStudent.getSelectedRow(), 0);
        Student student = studentDao.getStudentById(id);
        new JFrameUpdateStudent(student).setVisible(true);

    }//GEN-LAST:event_jButtonEditStudentActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        setStudentTable();
        setTeacherTable();
        setCourseTable();
        //(bunu mellimden sorush)

    }//GEN-LAST:event_formWindowGainedFocus

    private void jTextFieldSearchTeacherMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchTeacherMouseReleased

    }//GEN-LAST:event_jTextFieldSearchTeacherMouseReleased

    private void jTextFieldSearchTeacherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchTeacherKeyReleased
        DefaultTableModel dtm = (DefaultTableModel) jTableTeacher.getModel();
        String text = jTextFieldSearchTeacher.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dtm);
        jTableTeacher.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter("(?i)" + text));

    }//GEN-LAST:event_jTextFieldSearchTeacherKeyReleased

    private void jTextFieldSearchTeacherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchTeacherMouseEntered

    }//GEN-LAST:event_jTextFieldSearchTeacherMouseEntered

    private void jTextFieldSearchTeacherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchTeacherMouseExited

    }//GEN-LAST:event_jTextFieldSearchTeacherMouseExited

    private void jTextFieldSearchTeacherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchTeacherMousePressed


    }//GEN-LAST:event_jTextFieldSearchTeacherMousePressed

    private void jTextFieldSearchTeacherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchTeacherFocusGained
        if (jTextFieldSearchTeacher.getText().equals("Search...")) {
            jTextFieldSearchTeacher.setText("");
            jTextFieldSearchTeacher.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_jTextFieldSearchTeacherFocusGained

    private void jTextFieldSearchTeacherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchTeacherFocusLost
        if (jTextFieldSearchTeacher.getText().equals("")) {
            jTextFieldSearchTeacher.setText("Search...");
            jTextFieldSearchTeacher.setForeground(Color.GRAY);
        }


    }//GEN-LAST:event_jTextFieldSearchTeacherFocusLost
    private void jTextFieldSearchStudentKeyReleased(java.awt.event.KeyEvent evt) {
        DefaultTableModel dtm = (DefaultTableModel) jTableStudent.getModel();
        String text = jTextFieldSearchStudent.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dtm);
        jTableStudent.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter("(?i)" + text));

    }
    private void jTextFieldSearchStudentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchStudentFocusGained
        if (jTextFieldSearchStudent.getText().equals("Search...")) {
            jTextFieldSearchStudent.setText("");
            jTextFieldSearchStudent.setForeground(Color.GRAY);
        }


    }//GEN-LAST:event_jTextFieldSearchStudentFocusGained

    private void jTextFieldSearchStudentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchStudentFocusLost
        if (jTextFieldSearchStudent.getText().equals("")) {
            jTextFieldSearchStudent.setText("Search...");
            jTextFieldSearchStudent.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTextFieldSearchStudentFocusLost

    private void jTextFieldSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchStudentActionPerformed

    }//GEN-LAST:event_jTextFieldSearchStudentActionPerformed

    private void jButtonDeleteTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteTeacherActionPerformed
        Integer id = (Integer) jTableTeacher.getValueAt(jTableTeacher.getSelectedRow(), 0);
        if (id != null) {
            teacherDao.deleteTeacher(id);
            setTeacherTable();
        }
    }//GEN-LAST:event_jButtonDeleteTeacherActionPerformed

    private void jButtonEditCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditCourseActionPerformed
      
        jButtonUpdateCourse.setEnabled(true);
        jButtonRegisterCourse.setEnabled(false);
         idCourse = (Integer) jTableCourse.getValueAt(jTableCourse.getSelectedRow(), 0);
         Course course=courseDao.getCourseById(idCourse);
        jTextFieldCourseName.setText(course.getCourseName());
        jTextFieldDuration.setText(course.getDuration()+"");
       
    }//GEN-LAST:event_jButtonEditCourseActionPerformed

    private void jButtonDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCourseActionPerformed
        Integer id = (Integer) jTableCourse.getValueAt(jTableCourse.getSelectedRow(), 0);
        if (id != null) {
            courseDao.deleteCourse(id);
            setCourseTable();
        }
    }//GEN-LAST:event_jButtonDeleteCourseActionPerformed

    private void jTextFieldSearchCourseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchCourseFocusGained
          if (jTextFieldSearchCourse.getText().equals("Search...")) {
            jTextFieldSearchCourse.setText("");
            jTextFieldSearchCourse.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTextFieldSearchCourseFocusGained

    private void jTextFieldSearchCourseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchCourseFocusLost
         if (jTextFieldSearchCourse.getText().equals("")) {
            jTextFieldSearchCourse.setText("Search...");
            jTextFieldSearchCourse.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTextFieldSearchCourseFocusLost

    private void jTextFieldSearchCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchCourseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchCourseMouseEntered

    private void jTextFieldSearchCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchCourseMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchCourseMouseExited

    private void jTextFieldSearchCourseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchCourseMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchCourseMousePressed

    private void jTextFieldSearchCourseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchCourseMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchCourseMouseReleased

    private void jTextFieldSearchCourseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchCourseKeyReleased
        DefaultTableModel dtm = (DefaultTableModel) jTableCourse.getModel();
        String text = jTextFieldSearchCourse.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dtm);
        jTableCourse.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter("(?i)" + text));

    }//GEN-LAST:event_jTextFieldSearchCourseKeyReleased

    private void jButtonRegisterTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterTeacherActionPerformed
        
        String firstName=jTextFieldTeacherFirstName.getText();
        String lastName=jTextFieldTeacherLastName.getText();
        String courseName=(String) jComboBoxCourse1.getSelectedItem();
        
        Course course=new Course();
        course.setId(mapCourse.get(courseName));
        Teacher teacher=new Teacher(course,firstName,lastName);
        boolean result =teacherDao.registerNewTeacher(teacher, course);
         if(result){
            JOptionPane.showMessageDialog(null,Constants.REGISTER_MASSAGE );
        }else JOptionPane.showMessageDialog(this,Constants.ERROR_REGISETR_MASSAGE );
        
        
        
        
    }//GEN-LAST:event_jButtonRegisterTeacherActionPerformed

    private void jButtonUpdateTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateTeacherActionPerformed
         String teacherFirstName=jTextFieldTeacherFirstName.getText();
         String teacherLastName=jTextFieldTeacherLastName.getText();
         String courseName=(String)jComboBoxCourse1.getSelectedItem();
         Course course=new Course();
         course.setId(mapCourse.get(jComboBoxCourse1.getSelectedItem()));
        Teacher teacher=new Teacher();
        teacher.setFirstName(teacherFirstName);
        teacher.setLastName(teacherLastName);
        teacher.setCourse(course);
        teacher.setId(idTeacher);
        boolean result = teacherDao.updateTeacher(teacher);
        if(result){
            JOptionPane.showMessageDialog(null,Constants.REGISTER_MASSAGE );
           setTeacherTable();
        }else JOptionPane.showMessageDialog(this,Constants.ERROR_REGISETR_MASSAGE );
       
    }//GEN-LAST:event_jButtonUpdateTeacherActionPerformed

    private void jButtonUpdateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateCourseActionPerformed
      
        String courseName=jTextFieldCourseName.getText();
        int duration=Integer.parseInt(jTextFieldDuration.getText());
        Course course=new Course();
        course.setCourseName(courseName);
        course.setDuration(duration);
        course.setId(idCourse); 
        boolean result=courseDao.updateCourse(course);
         if(result){
            JOptionPane.showMessageDialog(null,Constants.REGISTER_MASSAGE );
            setCourseTable();
        }else JOptionPane.showMessageDialog(this,Constants.ERROR_REGISETR_MASSAGE );
        
    }//GEN-LAST:event_jButtonUpdateCourseActionPerformed

    private void jButtonRegisterCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterCourseActionPerformed
    
       String courseName=jTextFieldCourseName.getText();
        int duration=Integer.parseInt(jTextFieldDuration.getText());
        Course course=new Course();
        course.setCourseName(courseName);
        course.setDuration(duration);
       
        boolean result=courseDao.registerNewCourse(course);
         if(result){
            JOptionPane.showMessageDialog(null,Constants.REGISTER_MASSAGE );
            setCourseTable();
        }else JOptionPane.showMessageDialog(this,Constants.ERROR_REGISETR_MASSAGE );
    }//GEN-LAST:event_jButtonRegisterCourseActionPerformed

    private void jButtonResetTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetTeacherActionPerformed
        jTextFieldTeacherFirstName.setText("");
        jTextFieldTeacherLastName.setText("");
        jComboBoxCourse1.setSelectedIndex(0);
        jButtonUpdateTeacher.setEnabled(false);
        jButtonRegisterTeacher.setEnabled(true);
    }//GEN-LAST:event_jButtonResetTeacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAdmin().setVisible(true);
            }
        });
    }

    private void setStudentTable() {
        DefaultTableModel dtm = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        dtm.addColumn("ID");
        dtm.addColumn("Full name");
        dtm.addColumn("Phone number");
        dtm.addColumn("Teacher name");
        dtm.addColumn("Course name");
        dtm.addColumn("Course duration");

        List<Student> list = studentDao.getAllStudent();
        System.out.println(list);

        for (Student s : list) {
            String fullName = s.getFirstName() + " " + s.getLastName();
            String teacherFullName = s.getTeacher().getFirstName() + " " + s.getTeacher().getLastName();
            dtm.addRow(new Object[]{s.getId(), fullName, s.getTelephoneNumb(), teacherFullName, s.getTeacher().getCourse().getCourseName(), s.getTeacher().getCourse().getDuration()});
        }

        jTableStudent.setModel(dtm);

    }

    private void setTeacherTable() {
        DefaultTableModel dtm = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        dtm.addColumn("ID");
        dtm.addColumn("Teacher Full name");
        dtm.addColumn("Course name");
        dtm.addColumn("Course duration");
        List<Teacher> list = teacherDao.getAllTeacher();
        for (Teacher t : list) {
            String fullName = t.getFirstName() + " " + t.getLastName();
            dtm.addRow(new Object[]{t.getId(), fullName, t.getCourse().getCourseName(), t.getCourse().getDuration()});
        }

        jTableTeacher.setModel(dtm);

    }
     private void setCourseTable() {
        DefaultTableModel dtm = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
               
                return false;
            }
        };
        dtm.addColumn("ID");
        dtm.addColumn("Course name");
        dtm.addColumn("Duration");
        List<Course>list=courseDao.getAllCourse();
        for (Course c : list) {
            
            dtm.addRow(new Object[]{c.getId(), c.getCourseName(), c.getDuration()});
        }
        jTableCourse.setModel(dtm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteCourse;
    private javax.swing.JButton jButtonDeleteStudent;
    private javax.swing.JButton jButtonDeleteTeacher;
    private javax.swing.JButton jButtonEditCourse;
    private javax.swing.JButton jButtonEditStudent;
    private javax.swing.JButton jButtonEditTeacher;
    private javax.swing.JButton jButtonRegisterCourse;
    private javax.swing.JButton jButtonRegisterTeacher;
    private javax.swing.JButton jButtonResetCourse;
    private javax.swing.JButton jButtonResetTeacher;
    private javax.swing.JButton jButtonUpdateCourse;
    private javax.swing.JButton jButtonUpdateTeacher;
    private javax.swing.JComboBox<String> jComboBoxCourse1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelCourse;
    private javax.swing.JPanel jPanelStudent;
    private javax.swing.JPanel jPanelStudenttable;
    private javax.swing.JPanel jPanelTeacher;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPanelStudent;
    private javax.swing.JTabbedPane jTabbedAdmin;
    private javax.swing.JTable jTableCourse;
    private javax.swing.JTable jTableStudent;
    private javax.swing.JTable jTableTeacher;
    private javax.swing.JTextField jTextFieldCourseName;
    private javax.swing.JTextField jTextFieldDuration;
    private javax.swing.JTextField jTextFieldSearchCourse;
    private javax.swing.JTextField jTextFieldSearchStudent;
    private javax.swing.JTextField jTextFieldSearchTeacher;
    private javax.swing.JTextField jTextFieldTeacherFirstName;
    private javax.swing.JTextField jTextFieldTeacherLastName;
    // End of variables declaration//GEN-END:variables

    private void customInit() {
        jTableStudent.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                jButtonDeleteStudent.setEnabled(true);
                jButtonEditStudent.setEnabled(true);
            }
        });
        jTableTeacher.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                jButtonDeleteTeacher.setEnabled(true);
                jButtonEditTeacher.setEnabled(true);
            }
        });
        jTableCourse.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                jButtonEditCourse.setEnabled(true);
                jButtonDeleteCourse.setEnabled(true);
            }
        });
         List<Course> list = courseDao.getAllCourse();
        for (Course c : list) {
            jComboBoxCourse1.addItem(c.getCourseName());
             mapCourse.put(c.getCourseName(),c.getId());

        }

       

        jComboBoxCourse1.setSelectedIndex(0);
      
    }

}
